// <auto-generated />
using System;
using BeWarehouseHub.Core.Configurations;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BeWarehouseHub.Core.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251224015328_TenMigration")]
    partial class TenMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BeWarehouseHub.Domain.Models.AutoReorderSettings", b =>
                {
                    b.Property<Guid>("SettingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsAutoReorderEnabled")
                        .HasColumnType("boolean");

                    b.Property<int>("LeadTimeDays")
                        .HasColumnType("integer");

                    b.Property<int>("MaxStockLevel")
                        .HasColumnType("integer");

                    b.Property<int>("MinStockLevel")
                        .HasColumnType("integer");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<int>("ReorderPoint")
                        .HasColumnType("integer");

                    b.Property<int>("ReorderQuantity")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("WarehouseId")
                        .HasColumnType("uuid");

                    b.HasKey("SettingId");

                    b.HasIndex("ProductId");

                    b.HasIndex("WarehouseId");

                    b.ToTable("AutoReorderSettings");
                });

            modelBuilder.Entity("BeWarehouseHub.Domain.Models.Category", b =>
                {
                    b.Property<Guid>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("BeWarehouseHub.Domain.Models.DemandForecast", b =>
                {
                    b.Property<Guid>("ForecastId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Accuracy")
                        .HasColumnType("numeric(5,2)");

                    b.Property<int>("ActualDemand")
                        .HasColumnType("integer");

                    b.Property<string>("Algorithm")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ForecastPeriod")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<int>("PredictedDemand")
                        .HasColumnType("integer");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<int>("RecommendedOrderQuantity")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("SuggestedOrderDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("WarehouseId")
                        .HasColumnType("uuid");

                    b.HasKey("ForecastId");

                    b.HasIndex("ProductId");

                    b.HasIndex("WarehouseId");

                    b.ToTable("DemandForecasts");
                });

            modelBuilder.Entity("BeWarehouseHub.Domain.Models.ExportDetail", b =>
                {
                    b.Property<Guid>("ExportDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("BatchId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateExport")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ExportId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<Guid>("StockId")
                        .HasColumnType("uuid");

                    b.HasKey("ExportDetailId");

                    b.HasIndex("BatchId");

                    b.HasIndex("ExportId");

                    b.HasIndex("ProductId");

                    b.HasIndex("StockId");

                    b.ToTable("ExportDetails");
                });

            modelBuilder.Entity("BeWarehouseHub.Domain.Models.ExportReceipt", b =>
                {
                    b.Property<Guid>("ExportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CustomerAddress")
                        .HasColumnType("text");

                    b.Property<string>("CustomerName")
                        .HasColumnType("text");

                    b.Property<DateTime>("ExportDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("WarehouseId")
                        .HasColumnType("uuid");

                    b.HasKey("ExportId");

                    b.HasIndex("UserId");

                    b.HasIndex("WarehouseId");

                    b.ToTable("ExportReceipts");
                });

            modelBuilder.Entity("BeWarehouseHub.Domain.Models.ImportDetail", b =>
                {
                    b.Property<Guid>("ImportDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("BatchId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateImport")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ImportId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<Guid>("StockId")
                        .HasColumnType("uuid");

                    b.HasKey("ImportDetailId");

                    b.HasIndex("BatchId");

                    b.HasIndex("ImportId");

                    b.HasIndex("ProductId");

                    b.HasIndex("StockId");

                    b.ToTable("ImportDetails");
                });

            modelBuilder.Entity("BeWarehouseHub.Domain.Models.ImportReceipt", b =>
                {
                    b.Property<Guid>("ImportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ImportDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("WarehouseId")
                        .HasColumnType("uuid");

                    b.HasKey("ImportId");

                    b.HasIndex("UserId");

                    b.HasIndex("WarehouseId");

                    b.ToTable("ImportReceipts");
                });

            modelBuilder.Entity("BeWarehouseHub.Domain.Models.InventoryAudit", b =>
                {
                    b.Property<Guid>("AuditId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AuditCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("AuditDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("CompletedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("WarehouseId")
                        .HasColumnType("uuid");

                    b.HasKey("AuditId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("WarehouseId");

                    b.ToTable("InventoryAudits");
                });

            modelBuilder.Entity("BeWarehouseHub.Domain.Models.InventoryAuditDetail", b =>
                {
                    b.Property<Guid>("AuditDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ActualQuantity")
                        .HasColumnType("integer");

                    b.Property<Guid>("AuditId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AuditedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("AuditedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<int>("SystemQuantity")
                        .HasColumnType("integer");

                    b.Property<int>("Variance")
                        .HasColumnType("integer");

                    b.HasKey("AuditDetailId");

                    b.HasIndex("AuditId");

                    b.HasIndex("AuditedByUserId");

                    b.HasIndex("ProductId");

                    b.ToTable("InventoryAuditDetails");
                });

            modelBuilder.Entity("BeWarehouseHub.Domain.Models.Product", b =>
                {
                    b.Property<Guid>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Image")
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<Guid?>("SupplierId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Time")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("ProductId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("SupplierId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("BeWarehouseHub.Domain.Models.ProductBatch", b =>
                {
                    b.Property<Guid>("BatchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BatchNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal>("CostPrice")
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ManufactureDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("WarehouseId")
                        .HasColumnType("uuid");

                    b.HasKey("BatchId");

                    b.HasIndex("ProductId");

                    b.HasIndex("WarehouseId");

                    b.ToTable("ProductBatches");
                });

            modelBuilder.Entity("BeWarehouseHub.Domain.Models.Stock", b =>
                {
                    b.Property<Guid>("StockId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<Guid>("WarehouseId")
                        .HasColumnType("uuid");

                    b.HasKey("StockId");

                    b.HasIndex("ProductId");

                    b.HasIndex("WarehouseId");

                    b.ToTable("Stocks");
                });

            modelBuilder.Entity("BeWarehouseHub.Domain.Models.Supplier", b =>
                {
                    b.Property<Guid>("SupplierId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("SupplierName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("SupplierId");

                    b.ToTable("Suppliers");
                });

            modelBuilder.Entity("BeWarehouseHub.Domain.Models.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("BeWarehouseHub.Domain.Models.UserWarehouse", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("WarehouseId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserId", "WarehouseId");

                    b.HasIndex("WarehouseId");

                    b.ToTable("UserWarehouse");
                });

            modelBuilder.Entity("BeWarehouseHub.Domain.Models.Warehouse", b =>
                {
                    b.Property<Guid>("WarehouseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("WarehouseName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("WarehouseId");

                    b.ToTable("Warehouses");
                });

            modelBuilder.Entity("BeWarehouseHub.Domain.Models.AutoReorderSettings", b =>
                {
                    b.HasOne("BeWarehouseHub.Domain.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BeWarehouseHub.Domain.Models.Warehouse", "Warehouse")
                        .WithMany()
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("BeWarehouseHub.Domain.Models.DemandForecast", b =>
                {
                    b.HasOne("BeWarehouseHub.Domain.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BeWarehouseHub.Domain.Models.Warehouse", "Warehouse")
                        .WithMany()
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("BeWarehouseHub.Domain.Models.ExportDetail", b =>
                {
                    b.HasOne("BeWarehouseHub.Domain.Models.ProductBatch", "Batch")
                        .WithMany("ExportDetails")
                        .HasForeignKey("BatchId");

                    b.HasOne("BeWarehouseHub.Domain.Models.ExportReceipt", "ExportReceipt")
                        .WithMany("ExportDetails")
                        .HasForeignKey("ExportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BeWarehouseHub.Domain.Models.Product", "Product")
                        .WithMany("ExportDetails")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BeWarehouseHub.Domain.Models.Stock", "Stock")
                        .WithMany()
                        .HasForeignKey("StockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Batch");

                    b.Navigation("ExportReceipt");

                    b.Navigation("Product");

                    b.Navigation("Stock");
                });

            modelBuilder.Entity("BeWarehouseHub.Domain.Models.ExportReceipt", b =>
                {
                    b.HasOne("BeWarehouseHub.Domain.Models.User", "User")
                        .WithMany("ExportReceipts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BeWarehouseHub.Domain.Models.Warehouse", "Warehouse")
                        .WithMany("ExportReceipts")
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("BeWarehouseHub.Domain.Models.ImportDetail", b =>
                {
                    b.HasOne("BeWarehouseHub.Domain.Models.ProductBatch", "Batch")
                        .WithMany("ImportDetails")
                        .HasForeignKey("BatchId");

                    b.HasOne("BeWarehouseHub.Domain.Models.ImportReceipt", "ImportReceipt")
                        .WithMany("ImportDetails")
                        .HasForeignKey("ImportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BeWarehouseHub.Domain.Models.Product", "Product")
                        .WithMany("ImportDetails")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BeWarehouseHub.Domain.Models.Stock", "Stock")
                        .WithMany()
                        .HasForeignKey("StockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Batch");

                    b.Navigation("ImportReceipt");

                    b.Navigation("Product");

                    b.Navigation("Stock");
                });

            modelBuilder.Entity("BeWarehouseHub.Domain.Models.ImportReceipt", b =>
                {
                    b.HasOne("BeWarehouseHub.Domain.Models.User", "User")
                        .WithMany("ImportReceipts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BeWarehouseHub.Domain.Models.Warehouse", "Warehouse")
                        .WithMany("ImportReceipts")
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("BeWarehouseHub.Domain.Models.InventoryAudit", b =>
                {
                    b.HasOne("BeWarehouseHub.Domain.Models.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BeWarehouseHub.Domain.Models.Warehouse", "Warehouse")
                        .WithMany()
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedByUser");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("BeWarehouseHub.Domain.Models.InventoryAuditDetail", b =>
                {
                    b.HasOne("BeWarehouseHub.Domain.Models.InventoryAudit", "InventoryAudit")
                        .WithMany("InventoryAuditDetails")
                        .HasForeignKey("AuditId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BeWarehouseHub.Domain.Models.User", "AuditedByUser")
                        .WithMany()
                        .HasForeignKey("AuditedByUserId");

                    b.HasOne("BeWarehouseHub.Domain.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AuditedByUser");

                    b.Navigation("InventoryAudit");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("BeWarehouseHub.Domain.Models.Product", b =>
                {
                    b.HasOne("BeWarehouseHub.Domain.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId");

                    b.HasOne("BeWarehouseHub.Domain.Models.Supplier", "Supplier")
                        .WithMany("Products")
                        .HasForeignKey("SupplierId");

                    b.Navigation("Category");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("BeWarehouseHub.Domain.Models.ProductBatch", b =>
                {
                    b.HasOne("BeWarehouseHub.Domain.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BeWarehouseHub.Domain.Models.Warehouse", "Warehouse")
                        .WithMany()
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("BeWarehouseHub.Domain.Models.Stock", b =>
                {
                    b.HasOne("BeWarehouseHub.Domain.Models.Product", "Product")
                        .WithMany("Stocks")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BeWarehouseHub.Domain.Models.Warehouse", "Warehouse")
                        .WithMany("Stocks")
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("BeWarehouseHub.Domain.Models.UserWarehouse", b =>
                {
                    b.HasOne("BeWarehouseHub.Domain.Models.User", "User")
                        .WithMany("UserWarehouses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BeWarehouseHub.Domain.Models.Warehouse", "Warehouse")
                        .WithMany("UserWarehouses")
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("BeWarehouseHub.Domain.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("BeWarehouseHub.Domain.Models.ExportReceipt", b =>
                {
                    b.Navigation("ExportDetails");
                });

            modelBuilder.Entity("BeWarehouseHub.Domain.Models.ImportReceipt", b =>
                {
                    b.Navigation("ImportDetails");
                });

            modelBuilder.Entity("BeWarehouseHub.Domain.Models.InventoryAudit", b =>
                {
                    b.Navigation("InventoryAuditDetails");
                });

            modelBuilder.Entity("BeWarehouseHub.Domain.Models.Product", b =>
                {
                    b.Navigation("ExportDetails");

                    b.Navigation("ImportDetails");

                    b.Navigation("Stocks");
                });

            modelBuilder.Entity("BeWarehouseHub.Domain.Models.ProductBatch", b =>
                {
                    b.Navigation("ExportDetails");

                    b.Navigation("ImportDetails");
                });

            modelBuilder.Entity("BeWarehouseHub.Domain.Models.Supplier", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("BeWarehouseHub.Domain.Models.User", b =>
                {
                    b.Navigation("ExportReceipts");

                    b.Navigation("ImportReceipts");

                    b.Navigation("UserWarehouses");
                });

            modelBuilder.Entity("BeWarehouseHub.Domain.Models.Warehouse", b =>
                {
                    b.Navigation("ExportReceipts");

                    b.Navigation("ImportReceipts");

                    b.Navigation("Stocks");

                    b.Navigation("UserWarehouses");
                });
#pragma warning restore 612, 618
        }
    }
}
